name: "Bitacora digital "
description: "Datos generales de equipo que esta ingresando"
body:
- type: markdown
  attributes:
    value: "## Welcome!"
body:
- type: input
  id: prevalence
  attributes:
    label: Bug prevalences
    description: " que tansegudo "
    placeholder: " I visit a page" 
  validations:
    required: true
body:
- type: dropdown
  id: download
  attributes:  
    label: Marca de equipo a ingresar
    options:
      - Canon
      - Xerox
      - Hp
      - Epson
      - laser
      - Kyocera
  validations:
    required: False
