name: " Bitacora digital "
description: " Datos generales de equipo que esta ingresando"
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
body:
- type: dropdown
  id: download
  attributes:
    label: que modelo de euqipo es?
    options:
      - Hp
      - Epson
      - laser
      - inyeccion de tinta
  validations:
    required: true
