name: "Bitácora digital "
description: "Datos generales de equipo que esta ingresando"
body:
- type: input
  id: serie
  attributes:
    label: Número de serie
    description: "Ingresar el número de serie"
    placeholder: "serial no"
  validations:
    required: true  
- type: input
  id: prevalence
  attributes:
    label: Origen de equipo a revisar
    description: "Descripción de su area de adscripción"
    placeholder: "Zona, region o área"
  validations:
    required: true
